POST http://localhost:8080/achievements
Content-Type: application/json

{
  "name": "Novice Drinker",
  "description": "Drink your first cola",
  "points": 10
}

###

GET http://localhost:8080/achievements