POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "DtoMaster",
  "email": "test@valid.com"
}

###
GET http://localhost:8080/users

###
PUT http://localhost:8080/users/100
Content-Type: application/json

{
  "username": "RenamedUser",
  "email": "newemail@cola.cz"
}

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "Hacker",
  "email": "not-an-email"
}

###
POST http://localhost:8080/users/1/achievements/1

###
DELETE http://localhost:8080/users/1